# Generated by Django 5.0.6 on 2024-09-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('site_url', models.CharField(default='', max_length=200)),
                ('logo_url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
