# Generated by Django 5.0.6 on 2024-09-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_partner_logo_url_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
